use_frameworks!

target 'MyFirstPod_Example' do
  pod 'MyFirstPod', :path => '../'

  target 'MyFirstPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
